agent:
  label: jenkins-gradle6-java11
  container: gradle6-java11



pipelines:
  pullRequest:
    setVersion:
      steps:
        - sh: echo \$(jx-release-version)-SNAPSHOT > VERSION
          name: next-version
          comment: so we can retrieve the version in later steps
    build:
      options:
        sidecars:
          - image: docker:dind
            name: server
            securityContext:
              privileged: true
            volumeMounts:
              - mountPath: /var/lib/docker
                name: dind-storage
              - mountPath: /var/run/
                name: dind-socket
        volumes:
          - name: dind-storage
            emptyDir: { }
          - name: dind-socket
            emptyDir: { }
      steps:
        - sh: gradle -I /home/jenkins/.gradle/init.gradle clean build publish --info
          name: gradle-build
  release:
    setVersion:
      steps:
        - sh: echo \$(jx-release-version) > VERSION
          name: next-version
          comment: so we can retrieve the version in later steps
        - sh: jx step tag --version \$(cat VERSION)
          name: tag-version
    build:
      steps:
        - sh: gradle clean build
          name: gradle-build
    postBuild:
      steps:
        - sh: gradle -I /home/jenkins/.gradle/init.gradle publish -Pversion=\$(cat VERSION)
          name: gradle-publish