agent:
  label: jenkins-gradle6-java11
  container: gradle6-java11

pipelineConfig:
  pipelines:
    pullRequest:
      pipeline:
        options:
          volumes:
            - name: dind-storage
              emptyDir: { }
            - name: dind-socket
              emptyDir: { }
          sidecars:
            - image: docker:dind
              name: server
              securityContext:
                privileged: true
              volumeMounts:
                - mountPath: /var/lib/docker
                  name: dind-storage
                - mountPath: /var/run/
                  name: dind-socket
        stages:
          - name: setVersion
            steps:
              - sh: echo \$(jx-release-version)-SNAPSHOT > VERSION
                name: next-version
                comment: so we can retrieve the version in later steps
          - name: build
            steps:
              - sh: gradle -I /home/jenkins/.gradle/init.gradle clean build publish --info
                name: gradle-build
    release:
      pipeline:
        volumes:
          - name: dind-storage
            emptyDir: { }
          - name: dind-socket
            emptyDir: { }
        sidecars:
          - image: docker:dind
            name: server
            securityContext:
              privileged: true
            volumeMounts:
              - mountPath: /var/lib/docker
                name: dind-storage
              - mountPath: /var/run/
                name: dind-socket
        stages:
          - name: setVersion
            steps:
              - sh: echo \$(jx-release-version) > VERSION
                name: next-version
                comment: so we can retrieve the version in later steps
              - sh: jx step tag --version \$(cat VERSION)
                name: tag-version
          - name: build
            steps:
              - sh: gradle -I /home/jenkins/.gradle/init.gradle clean build publish
                name: gradle-build
