agent:
  label: jenkins-gradle6-java11
  container: gradle6-java11
pipelines:
  pullRequest:
    setVersion:
      steps:
        - sh: echo \$(jx-release-version)-SNAPSHOT > VERSION
          name: next-version
          comment: so we can retrieve the version in later steps
    build:
      steps:
        - sh: gradle -I /home/jenkins/.gradle/init.gradle clean build publish -Pversion=\$(cat VERSION) --info
          name: gradle-build
  release:
    setVersion:
      steps:
        - sh: echo \$(jx-release-version) > VERSION
          name: next-version
          comment: so we can retrieve the version in later step
        - sh: jx step tag --version \$(cat VERSION)
          name: tag-version
    build:
      steps:
        - sh: gradle -I /home/jenkins/.gradle/init.gradle clean build publish -Pversion=\$(cat VERSION) --info
          name: gradle-build